version: "3.9"
services:
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/backend

  celery-worker:
    container_name: celery-worker
    command: celery -A callboard_project worker -l INFO
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/backend
    depends_on:
      - backend
      - redis

#  celery-flower:
#    container_name: celery-flower
#    ports:
#      - "5555:5555"
#    command: flower -A callboard_project --port:5555 --broker=redis://:qwe123@redis:6379
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/backend
#    depends_on:
#      - backend
#      - redis

  redis:
    container_name: redis
    ports:
      - "6379:6379"
    image: bitnami/redis:6.0
    environment:
      - REDIS_PASSWORD=qwe123
      - REDIS_PORT=6379
