# Generated by Django 5.0.1 on 2024-01-25 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpost',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callboard.category'),
        ),
    ]
