# Generated by Django 4.2.2 on 2024-01-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0003_comment_post_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accept_status',
            field=models.BooleanField(default=False),
        ),
    ]
