# Generated by Django 4.2.2 on 2024-01-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0004_comment_accept_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='request_post',
            new_name='post',
        ),
    ]
